### ISSUE TITLE
Link to docs is broken

### ISSUE THREAD

**Issue by metaperl** [squirrels-nest/squirrels#24]
In the README https://github.com/squirrels-nest/squirrels?tab=readme-ov-file#squirrels this link is broken - https://github.com/squirrels-nest/squirrels?tab=readme-ov-file#squirrels

**Comment by ty2huang** [comment]
Thank you for raising this! And apologies for the late response. 

We recreated the website with a slightly different link but forgot to change the README until recently when I noticed this myself. The update can be found here:
https://github.com/squirrels-nest/squirrels/commit/5656ce01c37f3ad7c34b200819a7b3d5589f6ae8
